name: Build and Release

on:
  push:
    branches:
      - main  # Следи за веткой main, если используешь master, поменяй на master

jobs:
  build:
    runs-on: macos-latest  # Запуск на MacOS, можно сменить на windows-latest для Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Устанавливаем Node.js версии 16

    - name: Install dependencies
      run: |
        npm install

    - name: Build project
      run: |
        npm run build

    - name: Install electron dependencies
      run: |
        npm run postinstall

    - name: Build Electron app
      run: |
        npm run dist

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: 'dist/**/*'  # Путь до файлов для релиза

    - name: Publish release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create v1.0.0 dist/* --title "v1.0.0" --notes "First release of the app"
